### ISSUE TITLE
can't make phone calls - 'application error'

### ISSUE THREAD

**Issue by artsactiongroup** [18mr/action#41]
Hello
I've signed up with 2 addresses and prefer to use second one in Pennsylvania. When I entered my zipcode after the phone call, I got the 'application errror has occured' and call was terminated. 

Thanks for any help
Cindy Maguire

**Comment by catachresis** [comment]
Thanks for reporting this bug, Cindy. We've been seeing some errors like this and haven't had time to fully check it out. For the time being it seems like if you try again, the call should go through. Will update soon on fixes.

**Comment by catachresis** [comment]
Hi Cindy, as an update: we have updated our political data on Call Power, the tool that manages our phone calls, and it seems to have fixed a lot of the issues folks were having with this. Thanks again for reporting.
