### ISSUE TITLE
Getting antivirus error that don't purge my vote is an unsafe site

### ISSUE THREAD

**Issue by dianadillman** [18mr/action#49]
Getting antivirus error that don't purge my vote is an unsafe site

http://www.mcafee.com/threat-intelligence/site/default.aspx?url=http://action.18mr.org/dontpurgemyvote/

Says you need to open a trouble ticket here

https://www.trustedsource.org/?p=mcafee

**Comment by catachresis** [comment]
Hi Diana,

Thanks for filing this ticket. It's unclear what's going on here -- I wonder if surfing to the secure version of the site (https://action.18mr.org/dontpurgemyvote/) helps solve this issue? We're forcing HTTPS now, so that might be helpful.

**Comment by catachresis** [comment]
Changed settings to force HTTPS, so this issue should be resolved.
